global using TrucksInspections_ASP.NETCore_Angular_CleanArchitecture.Domain.Common;
global using TrucksInspections_ASP.NETCore_Angular_CleanArchitecture.Domain.Entities;
global using TrucksInspections_ASP.NETCore_Angular_CleanArchitecture.Domain.Enums;
global using TrucksInspections_ASP.NETCore_Angular_CleanArchitecture.Domain.Events;
global using TrucksInspections_ASP.NETCore_Angular_CleanArchitecture.Domain.Exceptions;
global using TrucksInspections_ASP.NETCore_Angular_CleanArchitecture.Domain.ValueObjects;